fypsite/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => 'users/registrations',
                                       :sessions => 'users/sessions'}

  resources :meetings
  resources :messages
  resources :users
  root 'pages#index'

  mount Refinery::Core::Engine, at: Refinery::Core.mounted_path

end

fypsite/app/models/meeting.rb
class Meeting < ActiveRecord::Base
  belongs_to :user #organiser
  has_many :meeting_attendees
  has_many :users, through: :meeting_attendees
end

fypsite/app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  def index
    @meetings = Meeting.all
  end

  def show
    @meeting = Meeting.find(params[:id])
  end

  def new
    @meeting = Meeting.new
  end

  def edit
    @meeting = Meeting.find(params[:id])
  end

  def create
    @meeting = Meeting.new(meeting_params)

    if @meeting.save
      redirect_to @meeting
    else
      render 'new'
    end
  end

  def update
    @meeting = Meeting.find(params[:id])

    if @meeting.update(meeting_params)
      redirect_to @meeting
    else
      render 'edit'
    end
  end

  def destroy
    @meeting = Meeting.find(params[:id])
    @meeting.destroy

    redirect_to meetings_path
  end

  private
  def meeting_params
    params.require(:meeting).permit(:subject, :date_and_time, :location, :agenda)
  end
end

fypsite/app/helpers/meetings_helper.rb
module MeetingsHelper
end

fypsite/app/views/meetings/_form.html.erb
<%= form_for @meeting do |f| %>

  <% if @meeting.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@meeting.errors.count, "error") %> prohibited
        this meeting from being saved:
      </h2>
      <ul>
        <% @meeting.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </p>

  <p>
    <%= f.label :date_and_time %><br>
    <%= f.text_area :date_and_time %>
  </p>

  <p>
    <%= f.label :location %><br>
    <%= f.text_area :location %>
  </p>

  <p>
    <%= f.label :agenda %><br>
    <%= f.text_area :agenda %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

fypsite/app/views/meetings/edit.html.erb
<h1>Edit Meeting</h1>

<%= render 'form' %>

<%= link_to 'Back', meetings_path %>

fypsite/app/views/meetings/index.html.erb
<h1>Listing Meetings</h1>

<%= link_to 'New Meeting', new_meeting_path %>

<table>
  <tr>
    <th>Subject</th>
    <th>Date and Time</th>
    <th>Location</th>
    <th>Agenda</th>
  </tr>

  <% @meetings.each do |meeting| %>
    <tr>
      <td><%= meeting.subject %></td>
      <td><%= meeting.date_and_time %></td>
      <td><%= meeting.location %></td>
      <td><%= meeting.agenda %></td>
      <td><%= link_to 'Show', meeting_path(meeting) %></td>
      <td><%= link_to 'Edit', edit_meeting_path(meeting) %></td>
      <td><%= link_to 'Destroy', meeting_path(meeting),
        method: :delete,
        data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

fypsite/app/views/meetings/new.html.erb
<h1>New Meeting</h1>

<%= render 'form' %>

<%= link_to 'Back', meetings_path %>

fypsite/app/views/meetings/show.html.erb
<p>
  <strong>Subject:</strong>
  <%= @meeting.subject %>
</p>

<p>
  <strong>Date and Time:</strong>
  <%= @meeting.date_and_time %>
</p>

<p>
  <strong>Location:</strong>
  <%= @meeting.location %>
</p>

<p>
  <strong>Agenda:</strong>
  <%= @meeting.agenda %>
</p>

<%= link_to 'Edit', edit_meeting_path(@meeting) %> |
<%= link_to 'Back', meetings_path %>