fypsite/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => 'users/registrations',
                                       :sessions => 'users/sessions'}

  resources :meetings
  resources :messages
  resources :users
  root 'pages#index'

  mount Refinery::Core::Engine, at: Refinery::Core.mounted_path

end

fypsite/app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user #sender
  has_many :message_recipients
  has_many :users, through: :message_recipients
end

fypsite/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages = Message.all
  end

  def show
    @message = Message.find(params[:id])
  end

  def new
    @message = Message.new
  end

  def edit
    @message = Message.find(params[:id])
  end

  def create
    @message = Message.new(message_params)
    @message.read = false
    @message.sender = current_user.id
    if @message.save
      redirect_to @message
    else
      render 'new'
    end
  end

  def update
    @message = Message.find(params[:id])

    if @message.update(message_params)
      redirect_to @message
    else
      render 'edit'
    end
  end

  def destroy
  end

  private
  def message_params
    params.require(:message).permit(:subject, :body, :read)
  end
end

fypsite/app/helpers/messages_helper.rb
module MessagesHelper
end

fypsite/app/views/messages/index.html.erb
<h1>Inbox</h1>

<% @messages.each do |message| %>
  <div class="message">
    <h2><%= message.subject %></h2>
    <p>Sent on: <%= message.details %> by <%= message.sender %></p>
    <p><%= message.read ? "Read" : "Unread" %></p>
    <p><%= link_to 'Show', message_path(message) %></p>
  </div>

<% end %>

<p><%= link_to 'New', new_message_path %></p>

fypsite/app/views/messages/new.html.erb
<%= form_for @message do |f| %>

  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@message.errors.count, "error") %> prohibited
        this message from being saved:
      </h2>
      <ul>
        <% @message.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :recipient %><br>
    <%= f.text_field :recipient %>
  </p>

  <p>
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

fypsite/app/views/messages/show.html.erb
<% @message.update_attribute(:read, true) # opens the message on viewing %>

<h1>Subject: <%= @message.subject %></h1>

<h2>Sent by: <%= @message.sender %></h2>
<h2>On: <%= @message.details %></h2>

<p><%= @message.body %></p>
<p><%= @message.read ? "Read" : "Unread" %></p>

<%= link_to 'Inbox', messages_path %>